"""Protocol definitions for SolArk Cloud API abstraction."""

from __future__ import annotations

from typing import Any, Protocol


class SolarkApiProtocol(Protocol):
    """Protocol for SolArk Cloud API clients."""

    async def async_authenticate(self) -> None: ...
    async def async_init(self) -> None: ...
    async def async_close(self) -> None: ...
    async def async_get_energy_year(self, plant_id: str, year: str) -> dict[str, Any]: ...
    async def async_get_energy_month(self, plant_id: str, date: str) -> dict[str, Any]: ...
    async def async_get_energy_day(self, plant_id: str, date: str) -> dict[str, Any]: ...
    async def async_get_today_energy(self, plant_id: str) -> dict[str, float]: ...
    async def async_get_current_month_energy(self, plant_id: str) -> dict[str, float]: ...
    async def async_get_current_year_energy(self, plant_id: str) -> dict[str, float]: ...
    async def async_get_realtime_power(self, plant_id: str) -> dict[str, float]: ...
    async def async_get_year_energy(self, plant_id: str, year: str) -> dict[str, dict[str, float]]: ...
